import {StyleSheet} from 'react-native';

export const editProfileStyles = (theme) => StyleSheet.create({
  background: {
    backgroundColor: theme.background,
    width: '100%',
    height: '100%',
    paddingBottom: 20,
    position: 'relative',
  },
  container: {
    flexGrow: 1,
    flexDirection: 'column',
    paddingVertical: 30,
    alignItems: 'center',
    width: '100%',
    gap: 50,
  },
  headingText: {
    color:theme.text,
    fontFamily: 'CircularStd-Bold',
    fontSize: 28,
    textAlign: 'center',
    paddingBottom: 20,
  },
  subHeadingText: {
    color:theme.text,
    fontFamily: 'CircularStd-Medium',
    fontSize: 20,
  },
  fieldContainer: {
    gap: 30,
    flexDirection: 'column',
    width: '100%',
    paddingHorizontal: 30,
  },
  form: {
    gap: 20,
    width: '100%',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  twoField: {
    flex: 1,
    width: '50%',
    gap: 10,
  },
  formField: {
    gap: 10,
    width: '100%',
  },
  inputTitle: {
    fontSize: 16,
    fontFamily: 'CircularStd-Medium',
    color:theme.text,
  },
  inputbox: {
    height: 54,
    width: '100%',
    color:theme.text,
    justifyContent: 'center',
    backgroundColor: theme.card,
    fontFamily: 'CircularStd-Regular',
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: theme.border,
  },
  bioInput: {
    height: 120,
    width: '100%',
    color:theme.text,
    backgroundColor: theme.card,
    fontFamily: 'CircularStd-Regular',
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: theme.border,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: '#ea324a',
    paddingVertical: 18,
    alignSelf: 'center',
    width: '84%',
    borderRadius: 10,
    marginTop: 40,
  },
  buttonText: {
    color:theme.text,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalContent: {
    backgroundColor: '#1E1E1E',
    width: '80%',
    gap: 10,
    padding: 20,
    borderRadius: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalOption: {
    fontSize: 18,
    width: '100%',
    paddingVertical: 10,
    color:theme.text,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
  selectionText: {
    height: 54,
    fontFamily: 'CircularStd-Regular',
    fontSize: 16,
    color: theme.text,
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: theme.card,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: theme.border,
  },
  disabledButton: {
    opacity: 0.5,
  },
  errorText: {
    fontFamily: 'CircularStd-Regular',
    color: 'red',
    fontSize: 15,
  },
});
