import {StyleSheet} from 'react-native';

export const userCreationStyles = theme =>
  StyleSheet.create({
    background: {
      height: '100%',
      backgroundColor: theme.background,
      position: 'relative',
    },
    form: {
      justifyContent: 'flex-start',
      gap: 30,
      paddingHorizontal: 30,
      paddingVertical: 30,
    },
    subHeadingText: {
      fontSize: 18,
      color: '#888',
      fontFamily: 'Outfit-regular',
      textAlign: 'center',
      paddingTop: 20,
      paddingBottom: 10,
      paddingHorizontal: 30,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    twoField: {
      flex: 1,
      gap: 10,
    },
    formField: {
      gap: 10,
    },
    inputTitle: {
      fontSize: 16,
      fontFamily: 'Outfit-medium',
      color: theme.text,
    },
    inputbox: {
      height: 54,
      color: theme.text,
      justifyContent: 'center',
      backgroundColor: theme.card,
      fontFamily: 'Outfit-regular',
      paddingHorizontal: 16,
      borderRadius: 10,
      borderWidth: 0.5,
      borderColor: theme.border,
    },
    bioInput: {
      height: 120,
      color: theme.text,
      backgroundColor: theme.card,
      fontFamily: 'Outfit-regular',
      paddingHorizontal: 16,
      borderRadius: 10,
      borderWidth: 0.5,
      borderColor: '#8C8C8C',
    },
    button: {
      backgroundColor: '#ea324a',
      paddingVertical: 18,
      alignSelf: 'center',
      width: '84%',
      borderRadius: 10,
      marginTop: 40,
    },
    buttonText: {
      color: theme.text,
      textAlign: 'center',
      fontSize: 20,
      fontWeight: '900',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    modalContent: {
      backgroundColor: theme.card,
      width: '80%',
      gap: 10,
      padding: 20,
      borderRadius: 20,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    modalOption: {
      fontSize: 18,
      width: '100%',
      paddingVertical: 10,
      color: theme.text,
    },
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      width: '100%',
      height: '100%',
      alignItems: 'center',
    },
    buttonContainer: {
      paddingHorizontal: 30,
      paddingBottom: 40,
      paddingTop: 20,
      backgroundColor: theme.background,
    },
    selectionText: {
      height: 54,
      fontFamily: 'Outfit-regular',
      fontSize: 16,
      color: '#888888',
      paddingVertical: 16,
      paddingHorizontal: 16,
      backgroundColor: theme.card,
      borderRadius: 10,
      borderWidth: 0.5,
      borderColor: theme.border,
    },
    container: {
      flex: 1,
      alignItems: 'center',
      gap: 50,
      justifyContent: 'center',
    },
    photoPicker: {
      width: 320,
      borderRadius: 160,
      borderWidth: 1,
      borderColor: theme.border,
      height: 320,
      backgroundColor: theme.card,
    },
    image: {width: '100%', height: '100%', borderRadius: 160},
    uploadOptions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 50,
    },
    optionButton: {
      height: 60,
      width: 60,
      borderRadius: 50,
      backgroundColor: theme.card,
      justifyContent: 'center',
      alignItems: 'center',
    },
    centerButton: {
      height: 75,
      width: 75,
      borderRadius: 50,
      backgroundColor: theme.card,
      justifyContent: 'center',
      alignItems: 'center',
    },
    placeholder: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    placeholderText: {
      color: '#888888',
      fontSize: 16,
      marginTop: 10,
    },
    disabledButton: {
      opacity: 0.5,
    },
    errorText: {
      fontFamily: 'Outfit-regular',
      color: 'red',
      fontSize: 15,
    },
  });
