import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: 'black',
    paddingVertical: 65,
    justifyContent: 'space-between',
    position:'relative',
  },
  backButtonContainer:{
    position:'absolute',
    top:'10%',
    left:20,
  },
  heading: {
    fontSize: 32,
    color: 'white',
    paddingBottom: 20,
    textAlign: 'center',
    fontFamily: 'Outfit-bold',
  },
  form: {
    gap: 20,
    paddingHorizontal: 30,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  twoField: {
    flex: 1,
    gap: 10,
  },
  formField: {
    gap: 10,
  },
  inputTitle: {
    fontSize: 16,
    fontFamily: 'Outfit-medium',
    color: 'white',
  },
  inputbox: {
    height: 54,
    color: 'white',
    backgroundColor: '#1A1A1A',
    fontFamily: 'Outfit-regular',
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#8C8C8C',
  },
  bioInput: {
    height: 120,
    color: 'white',
    backgroundColor: '#1A1A1A',
    fontFamily: 'Outfit-regular',
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#8C8C8C',
  },
  button: {
    backgroundColor: '#ea324a',
    paddingVertical: 18,
    alignSelf: 'center',
    width: '84%',
    borderRadius: 10,
    marginTop: 40,
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalContent: {
    backgroundColor: '#1E1E1E',
    width: '80%',
    gap: 10,
    padding: 20,
    borderRadius: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalOption: {
    fontSize: 18,
    width: '100%',
    paddingVertical: 10,
    color: 'white',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
  selectionText: {
    height: 54,
    fontFamily: 'Outfit-regular',
    fontSize: 16,
    color: '#D9D9D9',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#8C8C8C',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    gap: 50,
  },
  photoPicker: {
    width: 320,
    borderRadius: 160,
    borderWidth: 1,
    borderColor: 'white',
    height: 320,
    backgroundColor: '#1E1E1E',
  },
  image: {width: '100%', height: '100%', borderRadius: 160},
  uploadOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 50,
  },
  optionButton: {
    height: 60,
    width: 60,
    borderRadius: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerButton: {
    height: 75,
    width: 75,
    borderRadius: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: '#ccc',
    fontSize: 16,
    marginTop: 10,
  },
  disabledButton: {
    opacity: 0.5,
  },
  errorText:{
    fontFamily:'Outfit-regular',
    color: 'red',
    fontSize: 15,
  },
});
