import { StyleSheet } from 'react-native';

export const uploadBlogStyles = (theme) => StyleSheet.create({
  background: {
    height: '100%',
    width: '100%',
    backgroundColor: theme.background,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    width: '100%',
    height: '100%',
    gap: 30,
  },
  section: {
    alignItems: 'flex-start',
    gap: 16,
  },
  headingText: {
    fontFamily: 'CircularStd-Bold',
    fontSize: 24,
    color:theme.text,
  },
  uploadContainer: {
    backgroundColor: theme.card,
    width: '100%',
    borderRadius: 5,
    padding: 10,
    borderWidth: 0.5,
    gap: 20,
    borderColor: theme.border,
    flexDirection: 'column',
    alignItems: 'center',
  },
  blogImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  uploadBtn: {
    width: '100%',
    height: 50,
    backgroundColor: '#ED3147',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  richTextContainer: {
    borderRadius: 5,
    minHeight: 200,
    maxHeight: 400,
    borderWidth: 0.5,
    backgroundcolor:theme.text,
    width: '100%',
    borderColor: theme.border,
    overflow: 'hidden',
    paddingBottom: 50,
  },
  keyboardAvoidingView: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: theme.border,
    padding: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
});
