/* eslint-disable eslint-comments/no-unused-disable */
import {View, Text, ScrollView} from 'react-native';
import React from 'react';

const TabPhotos = () => {
  return (
    <View>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
      <Text>Photos</Text>
    </View>
  );
};

export default TabPhotos;
