/* eslint-disable react-native/no-inline-styles */
import React from 'react';
import {ScrollView, Text, StyleSheet, View, SafeAreaView} from 'react-native';
import {useTheme} from 'src/themes/useTheme';

const TermsAndConditions = () => {
  const termsSections = [
    {
      title: '1. Definitions',
      items: [
        '"Platform" refers to ClickedArt.com, including all associated websites, services, and tools.',
        '"User" refers to any individual or entity accessing the Platform, including photographers and buyers.',
        '"Photographer" refers to users who register to upload, share, and sell their photographs on the Platform.',
        '"Buyer" refers to users who purchase digital downloads or prints of photographs on the Platform.',
        '"Content" refers to images, text, metadata, and other materials uploaded by photographers or generated by the Platform.',
      ],
    },
    {
      title: '2. Acceptance of Terms',
      items: [
        'By registering, uploading content, purchasing, or otherwise interacting with the Platform, you acknowledge that you have read, understood, and agree to these Terms.',
        'These Terms may be updated from time to time. Continued use of the Platform after updates signifies acceptance of the revised Terms.',
      ],
    },
    {
      title: '3. Account Registration and Management',
      items: [
        'Eligibility: You must be at least 18 years old to register. For minors, a parent or legal guardian must supervise and consent.',
        'Account Security: Users are responsible for maintaining the confidentiality of their login credentials.',
        'Accurate Information: Users must provide accurate and up-to-date information during registration.',
        'Account Termination: ClickedArt reserves the right to suspend or terminate accounts for violation of these Terms or applicable laws.',
      ],
    },
    {
      title: '4. Photographer Guidelines',
      items: [
        'Content Upload: Photographers are responsible for ensuring that their uploaded content complies with copyright laws and does not infringe on the rights of others. Content must meet the quality standards outlined in our Upload Guidelines.',
        'Monetization: Photographers can apply for monetization after registration approval.\nRoyalty models:\n• Standard: 70% of net sales\n• Exclusive: 80% of net sales\nTaxes, including TDS, will be deducted as per government norms.',
        "Impact of Discounts on Royalties: When ClickedArt offers discounts or promotional pricing on photographs, the royalty amount payable to photographers will be calculated based on the discounted sale price. Photographers acknowledge and agree that such adjustments are part of the Platform's pricing strategy, and they shall not claim royalties based on the original, non-discounted price set for their content.",
        'Licensing and Usage: By uploading content, photographers grant ClickedArt a non-exclusive license to display, market, and sell their content. Photographers retain ownership but must ensure it is not sold with conflicting licenses elsewhere.',
        'Prohibited Content: Content must not include:\n• Nudity, hate speech, or violent imagery\n• Misleading or inaccurate metadata\n• Plagiarized or unlicensed images',
      ],
    },
    {
      title: '5. Buyer Guidelines',
      items: [
        'Purchasing Content: Buyers can purchase digital downloads or printed photographs based on the licensing options provided. All purchases are final, except in cases of damaged print orders.',
        'Licensing Terms: Buyers must adhere to the license terms specified at the time of purchase:\n• Standard License: Personal use only\n• Extended License: Commercial use permitted\n• Exclusive licenses may be arranged by contacting support.',
        'Prohibited Use: Buyers must not:\n• Resell purchased content without explicit permission\n• Remove watermarks from preview images\n• Use content in illegal or unethical activities',
      ],
    },
    {
      title: '6. Fees and Payments',
      items: [
        'Prices displayed on the Platform are inclusive of applicable taxes unless stated otherwise.',
        'Payment gateways ensure secure transactions. ClickedArt is not liable for third-party payment gateway issues.',
        'Photographers and buyers are responsible for any transaction fees imposed by financial institutions.',
      ],
    },
    {
      title: '7. Intellectual Property Rights',
      items: [
        'Photographers retain ownership of their content.',
        "ClickedArt's logo, design, and functionality are protected by intellectual property laws.",
        'Users must not copy, reverse-engineer, or modify any part of the Platform.',
      ],
    },
    {
      title: '8. Privacy and Data Protection',
      items: [
        'Users’ data is collected and processed in accordance with our Privacy Policy.',
        'Sensitive data, such as payment details, is encrypted for security purposes.',
        'Photographers consent to display their profile and portfolio publicly on the Platform.',
      ],
    },
    {
      title: '9. Dispute Resolution',
      items: [
        'Buyers and photographers are encouraged to resolve disputes amicably.',
        'In unresolved cases, ClickedArt may mediate but is not obligated to arbitrate disputes.',
        'Legal disputes will be subject to the jurisdiction of courts in [Lucknow/Uttar Pradesh].',
      ],
    },
    {
      title: '10. Prohibited Activities',
      items: [
        'Users must not:\n• Post false or misleading content\n• Attempt to hack or disrupt the Platform\n• Use the Platform for illegal activities',
      ],
    },
    {
      title: '11. Indemnification',
      items: [
        'Users agree to indemnify ClickedArt, its affiliates, and employees against any claims, damages, or liabilities arising from their use of the Platform or breach of these Terms.',
      ],
    },
    {
      title: '12. Limitation of Liability',
      items: [
        'ClickedArt is not liable for:\n• Loss of earnings for photographers\n• Errors in metadata provided by photographers\n• Issues arising from misuse of purchased content by buyers',
      ],
    },
    {
      title: '13. Termination',
      items: [
        'ClickedArt reserves the right to suspend or terminate user accounts for violations of these Terms.',
        'Users may terminate their accounts voluntarily by contacting support.',
      ],
    },
    {
      title: '14. Contact Information',
      items: [
        'For queries, feedback, or complaints, please contact ClickedArt at:',
        'Email: support@clickedart.com',
        'Phone: +91 7054001056',
      ],
    },
  ];

  const theme = useTheme();
  const styles = getStyles(theme);

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{marginTop: 20}}>
        <Text style={styles.lastUpdated}>Last Updated: 26 January 2025</Text>
        <Text style={styles.introText}>
          Welcome to ClickedArt.com! These Terms of Use ("Terms") govern your
          access to and use of the website and services provided by
          ClickedArt.com ("Platform"). By accessing or using the Platform, you
          agree to be bound by these Terms. If you do not agree, please refrain
          from using the Platform.
        </Text>
        {termsSections.map((section, index) => (
          <View key={index} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <View>
              {section.items.map((item, idx) => (
                <Text key={idx} style={styles.bullet}>
                  • {item}
                </Text>
              ))}
            </View>
          </View>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
};

const getStyles = theme =>
  StyleSheet.create({
    container: {
      paddingHorizontal: 20,
      paddingBottom: 20,
      backgroundColor: theme.background,
      position: 'relative',
      alignItems: 'flex-start',
    },
    title: {
      fontSize: 32,
      fontFamily: 'CircularStd-Bold',
      marginBottom: 10,
      color: theme.text,
      paddingVertical: 10,
    },
    lastUpdated: {
      fontSize: 16,
      color: '#888',
      marginBottom: 20,
    },
    introText: {
      fontSize: 15,
      marginBottom: 20,
      color: theme.text,
      lineHeight: 22,
    },
    section: {
      gap: 4,
      paddingVertical: 16,
      borderBottomcolor: theme.text,
      borderBottomWidth: 1,
    },
    sectionTitle: {
      fontSize: 18,
      fontFamily: 'CircularStd-Bold',
      marginBottom: 10,
      color: theme.text,
    },
    bullet: {
      fontSize: 16,
      lineHeight: 24,
      marginLeft: 10,
      marginBottom: 6,
      fontFamily: 'CircularStd-Medium',
      color: theme.text,
    },
  });

export default TermsAndConditions;
