import {StyleSheet} from 'react-native';

export const createProfileStyles = (theme) =>
  StyleSheet.create({
    background: {
      backgroundColor: theme.background,
      height: '100%',
      width: '100%',
    },
    headerIcons: {
      position: 'absolute',
      top: '25%',
      right: '4%',
      gap: 10,
      zIndex: 30,
    },
    iconContainer: {
      height: 30,
      width: 30,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 100,
      backgroundColor: theme.background,
    },
    profileHeader: {
      height: 200,
    },
    coverImageContainer: {
      height: '70%',
      width: '100%',
      position: 'relative',
    },
    coverImage: {
      height: '100%',
      width: '100%',
      resizeMode: 'cover',
    },
    profileDiv: {
      position: 'absolute',
      top: '40%',
      left: '50%',
      transform: [{translateX: -50}],
    },
    profileImage: {
      height: 110,
      width: 110,
      borderRadius: 100,
      borderColor: theme.background,
      borderWidth: 6,
    },
    edit: {
      backgroundColor: theme.text,
      justifyContent: 'center',
      alignItems: 'center',
      height: 24,
      width: 24,
      borderRadius: 20,
      position: 'absolute',
      zIndex: 10,
      bottom: 7,
      right: 5,
    },
    userDetails: {
      alignItems: 'center',
      gap: 10,
    },
    userName: {
      color: theme.text,
      fontFamily: 'Calibri-Medium',
      fontSize: 24,
      marginTop: 0,
    },
    userAddress: {
      color: '#888',
      fontFamily: 'Calibri-Medium',
      fontSize: 16,
    },
    userBio: {
      color: theme.text,
      fontFamily: 'Calibri-Medium',
      fontSize: 16,
      padding: 20,
      textAlign: 'justify',
      lineHeight: 20,
    },
    accountInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 28,
      gap: 40,
    },
    summary: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    title: {
      fontSize: 14,
      fontFamily: 'Calibri-Regular',
      color: theme.text,
    },
    count: {
      fontSize: 28,
      fontFamily: 'Calibri-Medium',
      color: theme.text,
    },
    tabsContainer: {
      marginTop: 0,
      gap: 35,
      width: '100%',
      alignSelf: 'center',
    },
    stickyTabs: {
      marginTop: 20,
      marginBottom: 10,
      gap: 35,
      width: '100%',
      alignSelf: 'center',
      paddingVertical: 12,
      backgroundColor: theme.background,
    },
    tabs: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 50,
      alignItems: 'center',
    },
    tabText: {
      fontSize: 20,
      lineHeight: 30,
      color: '#999',
      fontFamily: 'Calibri-Medium',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    modalContent: {
      backgroundColor: theme.card,
      width: '80%',
      gap: 10,
      padding: 20,
      borderRadius: 20,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 10,
      color: theme.text,
    },
    platformName: {
      fontSize: 18,
      width: '100%',
      paddingVertical: 10,
      color: theme.text,
    },
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      width: '100%',
      height: '100%',
      alignItems: 'center',
    },
  });
