import {StyleSheet} from 'react-native';

export const style = StyleSheet.create({
  background: {
    backgroundColor: 'black',
    height: '100%',
    width: '100%',
  },
  headerIcons: {
    position: 'absolute',
    top: '25%',
    right: '4%',
    gap: 10,
    zIndex: 30,
  },
  iconContainer: {
    height: 30,
    width: 30,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    backgroundColor: 'white',
  },
  profileHeader: {
    height: 200,
  },
  coverImageContainer: {
    height: '70%',
    width: '100%',
    position: 'relative',
  },
  coverImage: {
    height: '100%',
    width: '100%',
    resizeMode: 'cover',
  },
  profileDiv: {
    position: 'absolute',
    top: '40%',
    left: '50%',
    transform: [{translateX: -50}],
  },
  profileImage: {
    height: 110,
    width: 110,
    borderRadius: 100,
    borderColor: '#000',
    borderWidth: 6,
  },
  edit: {
    backgroundColor: 'white',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 24,
    width: 24,
    borderRadius: 20,
    position: 'absolute',
    zIndex: 10,
    bottom: 7,
    right: 5,
  },
  userDetails: {
    alignItems: 'center',
    gap: 10,
  },
  userName: {
    color: 'white',
    fontFamily: 'Outfit-medium',
    fontSize: 24,
    marginTop: 14,
  },
  userAddress: {
    color: '#D9D9D9',
    fontFamily: 'Outfit-medium',
    fontSize: 16,
  },
  userBio: {
    color: 'white',
    fontFamily: 'Outfit-medium',
    fontSize: 18,
    marginTop: 30,
  },
  accountInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    gap: 40,
  },
  summary: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  title: {
    fontSize: 14,
    fontFamily: 'Outfit-regular',
    color: 'white',
  },
  count: {
    fontSize: 28,
    fontFamily: 'Outfit-medium',
    color: 'white',
  },
  tabsContainer: {
    marginTop: 20,
    gap: 35,
    width: '100%',
    alignSelf: 'center',
  },
  stickyTabs: {
    marginTop: 40,
    gap: 35,
    width: '100%',
    alignSelf: 'center',
    paddingVertical: 20,
    backgroundColor: 'black',
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 50,
    alignItems: 'center',
  },
  tabText: {
    fontSize: 20,
    color: '#999',
    fontFamily: 'Outfit-medium',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalContent: {
    backgroundColor: '#1E1E1E',
    width: '80%',
    gap: 10,
    padding: 20,
    borderRadius: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalOptions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  platformName: {
    fontSize: 18,
    width: '100%',
    paddingVertical: 10,
    color: 'white',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
});
