import {StyleSheet} from 'react-native';

export const createTabStyles = (theme) => StyleSheet.create({
  container: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    flex: 1,
    paddingHorizontal: 10,
  },
  imageBorder: {
    width: 120,
    height: 120,
  },
  image: {
    resizeMode: 'cover',
    height: '100%',
    width: '100%',
  },
  imageDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  imageText: {
    fontSize: 16,
    width: '80%',
    fontFamily: 'Outfit-bold',
    color: theme.text,
  },
  status: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pending: {
    opacity: 0.8,
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  catalogueBorder: {
    padding: 15,
    gap: 24,
    width: '100%',
    flexGrow: 1,
    justifyContent: 'space-between',
    backgroundColor: theme.card,
    borderWidth: 0.5,
    borderColor: theme.border,
    borderRadius: 20,
    marginRight: 10,
    aspectRatio: 1,
  },
  imageDistribution: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: '5%',
  },
  catalogueImage: {
    width: '45%',
    height: '100%',
    borderRadius: 10,
    aspectRatio: 1,
  },
  catalogueImageExtra: {
    width: '45%',
    height: '100%',
    borderRadius: 10,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.background,
  },
  catalogueImageText: {
    fontSize: 32,
    fontFamily: 'Outfit-bold',
    color: theme.text,
    textAlign: 'center',
    paddingBottom: 5,
  },
  catalougeText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 24,
    color: theme.text,
  },
  noImageContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  noImageText: {
    fontSize: 32,
    fontFamily: 'Outfit-regular',
    color: '#A9A9A9',
    lineHeight: 40,
  },
  blogBorder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.text,
    width: '100%',
  },
  blogDetails: {
    flex: 1,
    gap: 8,
  },
  blogDate: {
    color: '#888',
    fontFamily: 'Outfit-bold',
    fontSize: 12,
  },
  blogImage: {
    height: 60,
    width: 60,
    borderRadius: 8,
  },
  imageContainer: {
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pendingContainer: {
    position: 'relative',
    opacity: 0.4,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalContent: {
    backgroundColor: theme.card,
    width: '85%',
    gap: 30,
    padding: 20,
    borderRadius: 20,
  },
  title: {
    fontSize: 24,
    fontFamily: 'Outfit-bold',
    color: theme.text,
    textAlign: 'center',
  },
  inputSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 16,
    width: '100%',
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Outfit-medium',
    color: theme.text,
  },
});
