import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 10,
    gap: 20,
  },
  imageBorder: {
    paddingTop: 8,
    paddingBottom: 10,
    paddingHorizontal: 10,
    width: '47%',
    height: 190,
    justifyContent: 'space-between',
    backgroundColor: '#1A1A1A',
    borderWidth: 0.5,
    borderColor: 'white',
    borderRadius: 10,
  },
  image: {
    resizeMode: 'cover',
    height: '80%',
    width: '100%',
  },
  imageDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  imageText: {
    fontSize: 16,
    width: '80%',
    fontFamily: 'Outfit-bold',
    color: 'white',
  },
  catalogueBorder: {
    padding: 15,
    gap: 24,
    width: '100%',
    flexGrow: 1,
    justifyContent: 'space-between',
    backgroundColor: '#1A1A1A',
    borderWidth: 0.5,
    borderColor: 'white',
    borderRadius: 20,
    marginRight: 10,
    minHeight: 400,
  },
  imageDistribution: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  catalogueImage: {
    width: 150,
    height: 150,
  },
  catalougeText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 24,
    color: 'white',
  },
  blogBorder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'white',
    width: '100%',
  },
  blogDetails: {
    flex: 1,
    gap: 8,
  },
  blogDate: {
    color: '#A9A9A9',
    fontFamily: 'Outfit-bold',
    fontSize: 12,
  },
  blogImage: {
    height: 60,
    width: 60,
    borderRadius: 8,
  },
  imageContainer: {
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
